const gameFsm = {
  IDLE: "IDLE",
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  RESUME: "RESUME",
  FINISHED: "FINISHED"
};
const DECREMENT_MATCH_COUNT = "DECREMENT_MATCH_COUNT";
const SET_MATCH_PAIRS = "SET_MATCH_PAIRS";

const timerActions = {
  SET_MEM_TIME: "SET_MEM_TIME",
  INCREMENT_TIMER: "INCREMENT_TIMER",
  RESET_TIMER: "RESET_TIMER",
  RECORD_TIME: "RECORD_TIME",
  SET_INTERVAL_ID: "SET_INTERVAL_ID"
};

const matchActions = {
  MATCH: "MATCH_MATCH",
  RESET: "MATCH_REST"
};
const matchResult = {
  MATCH_NO_RESULT: "MATCH_NO_RESULT",
  MATCH_SUCCESS: "MATCH_SUCCESS",
  MATCH_FAILURE: "MATCH_FAILURE"
};

const INIT_CONFIG = "INIT_CONFIG";
const SET_CONFIG = "SET_CONFIG";

export {
  gameFsm,
  DECREMENT_MATCH_COUNT,
  SET_MATCH_PAIRS,
  timerActions,
  matchActions,
  matchResult,
  INIT_CONFIG,
  SET_CONFIG
};
